# Use scoring_bot env
# Used to tally points from extracted WhatsApp chat

In [1]:
import pandas as pd
import polars as pl
import re
from wordle_bot.whatsapp import Database
from wordle_bot.scorer import ScoreCalculator as SC
from datetime import datetime
import wordle_bot.parser as parser

In [2]:
with open('WhatsApp Chat with Wordle Golf example.txt', 'r', encoding = 'utf-8') as f:
    lines = f.readlines()

for line in lines[80:120]:
    print(line.strip())

🟨⬛⬛⬛⬛
⬛⬛🟨🟩⬛
⬛⬛⬛🟩🟨
🟩🟩🟩🟩🟩
1/26/26, 11:29 AM - H: Wordle 1,682 4/6*

⬜⬜⬜⬜🟩
⬜🟩🟨⬜🟩
⬜🟩🟩🟩🟩
🟩🟩🟩🟩🟩
1/26/26, 7:20 PM - P: Wordle 1,683 5/6*

⬛⬛⬛🟨⬛
🟨⬛⬛🟨⬛
⬛🟩🟩⬛🟩
⬛🟩🟩🟩🟩
🟩🟩🟩🟩🟩
1/26/26, 7:32 PM - J: Scores as of yesterday:

AHJ 9
M 8
CDZ 7
P 5
1/26/26, 7:35 PM - J: Wordle 1,683 5/6*

⬜⬜⬜⬜⬜
⬜⬜🟨⬜⬜
⬜⬜🟨⬜⬜
⬜🟩🟩🟩🟩
🟩🟩🟩🟩🟩
1/26/26, 7:35 PM - D: Wordle 1,683 5/6*

🟨⬜⬜⬜⬜
⬜⬜⬜🟨⬜
🟨🟨⬜⬜⬜
⬜🟩🟩⬜🟩
🟩🟩🟩🟩🟩
1/26/26, 8:08 PM - A: Wordle 1,683 4/6*

In [3]:
print(lines[8082:8084])

['6/18/26, 9:13\u202fPM - Z: Happy 5th Birthday Wordle 🎂\n', 'Wordle 1,826 5/6*\n']

In [4]:
result_lines = parser.parser_wordle_score(lines)
print(result_lines[:5])

[('D', 1681, '3'), ('H', 1681, '5'), ('J', 1682, '4'), ('A', 1682, '4'), ('M', 1682, '5')]

In [5]:
scores_extract = [SC(player, wordle, score) for player, wordle, score in result_lines]

In [6]:
print(scores_extract[:5])

[(player=D, wordle=1681, score=3)
, (player=H, wordle=1681, score=5)
, (player=J, wordle=1682, score=4)
, (player=A, wordle=1682, score=4)
, (player=M, wordle=1682, score=5)
]

In [7]:
# Change a line to X
# Test for failed wordle

scores_extract[1].score = "X"

# delete a line to test for missed wordle

scores_extract.pop(2)

(player=J, wordle=1682, score=4)

In [8]:
print(scores_extract[0:10])

[(player=D, wordle=1681, score=3)
, (player=H, wordle=1681, score=X)
, (player=A, wordle=1682, score=4)
, (player=M, wordle=1682, score=5)
, (player=C, wordle=1682, score=4)
, (player=D, wordle=1682, score=4)
, (player=P, wordle=1682, score=2)
, (player=Z, wordle=1682, score=4)
, (player=H, wordle=1682, score=4)
, (player=P, wordle=1683, score=5)
]

In [9]:
# Add random
test_list = [["Test", 1689,5], 
             ["Test", 1695,4], 
             ["Test", 1705,'X'],
             ["Test", 1720,2],
             ["Test", 1722,1]]

test_SC_list = [SC(player, wordle, score) for player, wordle, score in test_list]

scores_extract.extend(test_SC_list)
print(test_SC_list)

[(player=Test, wordle=1689, score=5)
, (player=Test, wordle=1695, score=4)
, (player=Test, wordle=1705, score=X)
, (player=Test, wordle=1720, score=2)
, (player=Test, wordle=1722, score=1)
]

In [10]:
df = SC.score_cleaner(scores_extract)
print(df)

shape: (1_558, 3)
┌────────┬────────────┬───────┐
│ player ┆ wordle_num ┆ score │
│ ---    ┆ ---        ┆ ---   │
│ str    ┆ i64        ┆ i64   │
╞════════╪════════════╪═══════╡
│ A      ┆ 1681       ┆ 7     │
│ C      ┆ 1681       ┆ 7     │
│ D      ┆ 1681       ┆ 3     │
│ H      ┆ 1681       ┆ 7     │
│ J      ┆ 1681       ┆ 7     │
│ …      ┆ …          ┆ …     │
│ J      ┆ 1853       ┆ 7     │
│ M      ┆ 1853       ┆ 5     │
│ P      ┆ 1853       ┆ 7     │
│ Test   ┆ 1853       ┆ 7     │
│ Z      ┆ 1853       ┆ 7     │
└────────┴────────────┴───────┘

In [11]:
print(df[:10])

shape: (10, 3)
┌────────┬────────────┬───────┐
│ player ┆ wordle_num ┆ score │
│ ---    ┆ ---        ┆ ---   │
│ str    ┆ i64        ┆ i64   │
╞════════╪════════════╪═══════╡
│ A      ┆ 1681       ┆ 7     │
│ C      ┆ 1681       ┆ 7     │
│ D      ┆ 1681       ┆ 3     │
│ H      ┆ 1681       ┆ 7     │
│ J      ┆ 1681       ┆ 7     │
│ M      ┆ 1681       ┆ 7     │
│ P      ┆ 1681       ┆ 7     │
│ Test   ┆ 1681       ┆ 7     │
│ Z      ┆ 1681       ┆ 7     │
│ A      ┆ 1682       ┆ 4     │
└────────┴────────────┴───────┘

In [12]:
print(df['wordle_num'][0])
print(df['wordle_num'].unique())

1681
shape: (173,)
Series: 'wordle_num' [i64]
[
	1681
	1682
	1683
	1684
	1685
	…
	1849
	1850
	1851
	1852
	1853
]

In [13]:
print(df)

shape: (1_558, 3)
┌────────┬────────────┬───────┐
│ player ┆ wordle_num ┆ score │
│ ---    ┆ ---        ┆ ---   │
│ str    ┆ i64        ┆ i64   │
╞════════╪════════════╪═══════╡
│ A      ┆ 1681       ┆ 7     │
│ C      ┆ 1681       ┆ 7     │
│ D      ┆ 1681       ┆ 3     │
│ H      ┆ 1681       ┆ 7     │
│ J      ┆ 1681       ┆ 7     │
│ …      ┆ …          ┆ …     │
│ J      ┆ 1853       ┆ 7     │
│ M      ┆ 1853       ┆ 5     │
│ P      ┆ 1853       ┆ 7     │
│ Test   ┆ 1853       ┆ 7     │
│ Z      ┆ 1853       ┆ 7     │
└────────┴────────────┴───────┘

In [14]:
weekly_scores = SC.week_ranking(df)
print(weekly_scores[3])

shape: (9, 4)
┌────────┬───────┬─────────────┬──────┐
│ player ┆ score ┆ wordle_week ┆ rank │
│ ---    ┆ ---   ┆ ---         ┆ ---  │
│ str    ┆ i64   ┆ str         ┆ f64  │
╞════════╪═══════╪═════════════╪══════╡
│ H      ┆ 25    ┆ 1702-1708   ┆ 1.5  │
│ M      ┆ 25    ┆ 1702-1708   ┆ 1.5  │
│ D      ┆ 26    ┆ 1702-1708   ┆ 3.0  │
│ C      ┆ 27    ┆ 1702-1708   ┆ 4.0  │
│ A      ┆ 28    ┆ 1702-1708   ┆ 6.0  │
│ Z      ┆ 28    ┆ 1702-1708   ┆ 6.0  │
│ J      ┆ 28    ┆ 1702-1708   ┆ 6.0  │
│ P      ┆ 32    ┆ 1702-1708   ┆ 8.0  │
│ Test   ┆ 49    ┆ 1702-1708   ┆ 9.0  │
└────────┴───────┴─────────────┴──────┘

In [15]:
for weekly_score in weekly_scores:
    # print(weekly_score)

    # competition ranking with mean ranks
    df_ranked  = weekly_score.with_columns(
        pl.arange(1, weekly_score.height +1).alias("raw_rank")
    )

    # print(df_ranked)

# compute mean ranks per score group

    df_ranked_grouped = df_ranked.group_by("score").agg(
        pl.col("raw_rank").mean().alias("rank")
    )

    df_final = df_ranked.join(df_ranked_grouped, on="score", how="left").sort("rank")
    df_final = df_final.drop("raw_rank")

    print(df_final)

shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ A      ┆ 27    ┆ 1681-1687   ┆ 1.0  ┆ 1.0        │
│ P      ┆ 29    ┆ 1681-1687   ┆ 3.0  ┆ 3.0        │
│ D      ┆ 29    ┆ 1681-1687   ┆ 3.0  ┆ 3.0        │
│ C      ┆ 29    ┆ 1681-1687   ┆ 3.0  ┆ 3.0        │
│ M      ┆ 30    ┆ 1681-1687   ┆ 5.0  ┆ 5.0        │
│ H      ┆ 32    ┆ 1681-1687   ┆ 6.5  ┆ 6.5        │
│ Z      ┆ 32    ┆ 1681-1687   ┆ 6.5  ┆ 6.5        │
│ J      ┆ 36    ┆ 1681-1687   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1681-1687   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ P      ┆ 28    ┆ 1688-1694   ┆ 1.5  ┆ 1.5        │
│ H      ┆ 28    ┆ 1688-1694   ┆ 1.5  ┆ 1.5        │
│ J      ┆ 30    ┆ 1688-1694   ┆ 4.5  ┆ 4.5        │
│ Z      ┆ 30    ┆ 1688-1694   ┆ 4.5  ┆ 4.5        │
│ C      ┆ 30    ┆ 1688-1694   ┆ 4.5  ┆ 4.5        │
│ M      ┆ 30    ┆ 1688-1694   ┆ 4.5  ┆ 4.5        │
│ D      ┆ 32    ┆ 1688-1694   ┆ 7.5  ┆ 7.5        │
│ A      ┆ 32    ┆ 1688-1694   ┆ 7.5  ┆ 7.5        │
│ Test   ┆ 47    ┆ 1688-1694   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ M      ┆ 26    ┆ 1695-1701   ┆ 1.0  ┆ 1.0        │
│ P      ┆ 28    ┆ 1695-1701   ┆ 2.5  ┆ 2.5        │
│ C      ┆ 28    ┆ 1695-1701   ┆ 2.5  ┆ 2.5        │
│ H      ┆ 32    ┆ 1695-1701   ┆ 4.0  ┆ 4.0        │
│ A      ┆ 33    ┆ 1695-1701   ┆ 5.5  ┆ 5.5        │
│ Z      ┆ 33    ┆ 1695-1701   ┆ 5.5  ┆ 5.5        │
│ D      ┆ 34    ┆ 1695-1701   ┆ 7.0  ┆ 7.0        │
│ J      ┆ 35    ┆ 1695-1701   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 46    ┆ 1695-1701   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ H      ┆ 25    ┆ 1702-1708   ┆ 1.5  ┆ 1.5        │
│ M      ┆ 25    ┆ 1702-1708   ┆ 1.5  ┆ 1.5        │
│ D      ┆ 26    ┆ 1702-1708   ┆ 3.0  ┆ 3.0        │
│ C      ┆ 27    ┆ 1702-1708   ┆ 4.0  ┆ 4.0        │
│ A      ┆ 28    ┆ 1702-1708   ┆ 6.0  ┆ 6.0        │
│ Z      ┆ 28    ┆ 1702-1708   ┆ 6.0  ┆ 6.0        │
│ J      ┆ 28    ┆ 1702-1708   ┆ 6.0  ┆ 6.0        │
│ P      ┆ 32    ┆ 1702-1708   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1702-1708   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 22    ┆ 1709-1715   ┆ 1.0  ┆ 1.0        │
│ Z      ┆ 26    ┆ 1709-1715   ┆ 2.0  ┆ 2.0        │
│ H      ┆ 29    ┆ 1709-1715   ┆ 3.5  ┆ 3.5        │
│ J      ┆ 29    ┆ 1709-1715   ┆ 3.5  ┆ 3.5        │
│ M      ┆ 31    ┆ 1709-1715   ┆ 5.0  ┆ 5.0        │
│ D      ┆ 33    ┆ 1709-1715   ┆ 6.5  ┆ 6.5        │
│ A      ┆ 33    ┆ 1709-1715   ┆ 6.5  ┆ 6.5        │
│ P      ┆ 35    ┆ 1709-1715   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1709-1715   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ A      ┆ 25    ┆ 1716-1722   ┆ 1.0  ┆ 1.0        │
│ M      ┆ 27    ┆ 1716-1722   ┆ 2.0  ┆ 2.0        │
│ J      ┆ 28    ┆ 1716-1722   ┆ 4.0  ┆ 4.0        │
│ D      ┆ 28    ┆ 1716-1722   ┆ 4.0  ┆ 4.0        │
│ H      ┆ 28    ┆ 1716-1722   ┆ 4.0  ┆ 4.0        │
│ C      ┆ 29    ┆ 1716-1722   ┆ 6.0  ┆ 6.0        │
│ Z      ┆ 32    ┆ 1716-1722   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 33    ┆ 1716-1722   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 38    ┆ 1716-1722   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 26    ┆ 1723-1729   ┆ 1.5  ┆ 1.5        │
│ M      ┆ 26    ┆ 1723-1729   ┆ 1.5  ┆ 1.5        │
│ H      ┆ 27    ┆ 1723-1729   ┆ 3.0  ┆ 3.0        │
│ J      ┆ 30    ┆ 1723-1729   ┆ 4.0  ┆ 4.0        │
│ A      ┆ 31    ┆ 1723-1729   ┆ 5.0  ┆ 5.0        │
│ Z      ┆ 32    ┆ 1723-1729   ┆ 6.0  ┆ 6.0        │
│ P      ┆ 33    ┆ 1723-1729   ┆ 7.0  ┆ 7.0        │
│ D      ┆ 36    ┆ 1723-1729   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1723-1729   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 25    ┆ 1730-1736   ┆ 1.0  ┆ 1.0        │
│ D      ┆ 27    ┆ 1730-1736   ┆ 3.0  ┆ 3.0        │
│ A      ┆ 27    ┆ 1730-1736   ┆ 3.0  ┆ 3.0        │
│ M      ┆ 27    ┆ 1730-1736   ┆ 3.0  ┆ 3.0        │
│ J      ┆ 28    ┆ 1730-1736   ┆ 5.5  ┆ 5.5        │
│ H      ┆ 28    ┆ 1730-1736   ┆ 5.5  ┆ 5.5        │
│ Z      ┆ 29    ┆ 1730-1736   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 31    ┆ 1730-1736   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1730-1736   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ Z      ┆ 27    ┆ 1737-1743   ┆ 1.5  ┆ 1.5        │
│ M      ┆ 27    ┆ 1737-1743   ┆ 1.5  ┆ 1.5        │
│ A      ┆ 28    ┆ 1737-1743   ┆ 3.0  ┆ 3.0        │
│ P      ┆ 29    ┆ 1737-1743   ┆ 4.0  ┆ 4.0        │
│ C      ┆ 30    ┆ 1737-1743   ┆ 5.5  ┆ 5.5        │
│ J      ┆ 30    ┆ 1737-1743   ┆ 5.5  ┆ 5.5        │
│ H      ┆ 31    ┆ 1737-1743   ┆ 7.5  ┆ 7.5        │
│ D      ┆ 31    ┆ 1737-1743   ┆ 7.5  ┆ 7.5        │
│ Test   ┆ 49    ┆ 1737-1743   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ M      ┆ 21    ┆ 1744-1750   ┆ 1.0  ┆ 1.0        │
│ A      ┆ 26    ┆ 1744-1750   ┆ 2.5  ┆ 2.5        │
│ P      ┆ 26    ┆ 1744-1750   ┆ 2.5  ┆ 2.5        │
│ C      ┆ 27    ┆ 1744-1750   ┆ 4.0  ┆ 4.0        │
│ Z      ┆ 30    ┆ 1744-1750   ┆ 5.5  ┆ 5.5        │
│ J      ┆ 30    ┆ 1744-1750   ┆ 5.5  ┆ 5.5        │
│ D      ┆ 31    ┆ 1744-1750   ┆ 7.0  ┆ 7.0        │
│ H      ┆ 32    ┆ 1744-1750   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1744-1750   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ A      ┆ 24    ┆ 1751-1757   ┆ 1.0  ┆ 1.0        │
│ C      ┆ 25    ┆ 1751-1757   ┆ 2.0  ┆ 2.0        │
│ M      ┆ 26    ┆ 1751-1757   ┆ 3.0  ┆ 3.0        │
│ H      ┆ 27    ┆ 1751-1757   ┆ 4.5  ┆ 4.5        │
│ D      ┆ 27    ┆ 1751-1757   ┆ 4.5  ┆ 4.5        │
│ P      ┆ 29    ┆ 1751-1757   ┆ 6.0  ┆ 6.0        │
│ J      ┆ 32    ┆ 1751-1757   ┆ 7.0  ┆ 7.0        │
│ Z      ┆ 33    ┆ 1751-1757   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1751-1757   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ A      ┆ 27    ┆ 1758-1764   ┆ 1.0  ┆ 1.0        │
│ H      ┆ 28    ┆ 1758-1764   ┆ 3.0  ┆ 3.0        │
│ D      ┆ 28    ┆ 1758-1764   ┆ 3.0  ┆ 3.0        │
│ Z      ┆ 28    ┆ 1758-1764   ┆ 3.0  ┆ 3.0        │
│ C      ┆ 29    ┆ 1758-1764   ┆ 5.5  ┆ 5.5        │
│ J      ┆ 29    ┆ 1758-1764   ┆ 5.5  ┆ 5.5        │
│ P      ┆ 33    ┆ 1758-1764   ┆ 7.0  ┆ 7.0        │
│ M      ┆ 34    ┆ 1758-1764   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1758-1764   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 23    ┆ 1765-1771   ┆ 1.0  ┆ 1.0        │
│ J      ┆ 28    ┆ 1765-1771   ┆ 2.5  ┆ 2.5        │
│ D      ┆ 28    ┆ 1765-1771   ┆ 2.5  ┆ 2.5        │
│ Z      ┆ 29    ┆ 1765-1771   ┆ 5.0  ┆ 5.0        │
│ M      ┆ 29    ┆ 1765-1771   ┆ 5.0  ┆ 5.0        │
│ A      ┆ 29    ┆ 1765-1771   ┆ 5.0  ┆ 5.0        │
│ H      ┆ 33    ┆ 1765-1771   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 39    ┆ 1765-1771   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1765-1771   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ P      ┆ 26    ┆ 1772-1778   ┆ 1.0  ┆ 1.0        │
│ A      ┆ 27    ┆ 1772-1778   ┆ 2.5  ┆ 2.5        │
│ C      ┆ 27    ┆ 1772-1778   ┆ 2.5  ┆ 2.5        │
│ M      ┆ 28    ┆ 1772-1778   ┆ 4.0  ┆ 4.0        │
│ H      ┆ 29    ┆ 1772-1778   ┆ 5.0  ┆ 5.0        │
│ D      ┆ 30    ┆ 1772-1778   ┆ 6.5  ┆ 6.5        │
│ J      ┆ 30    ┆ 1772-1778   ┆ 6.5  ┆ 6.5        │
│ Z      ┆ 31    ┆ 1772-1778   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1772-1778   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ M      ┆ 28    ┆ 1779-1785   ┆ 1.0  ┆ 1.0        │
│ C      ┆ 29    ┆ 1779-1785   ┆ 2.5  ┆ 2.5        │
│ P      ┆ 29    ┆ 1779-1785   ┆ 2.5  ┆ 2.5        │
│ H      ┆ 30    ┆ 1779-1785   ┆ 4.5  ┆ 4.5        │
│ A      ┆ 30    ┆ 1779-1785   ┆ 4.5  ┆ 4.5        │
│ Z      ┆ 33    ┆ 1779-1785   ┆ 6.0  ┆ 6.0        │
│ D      ┆ 36    ┆ 1779-1785   ┆ 7.0  ┆ 7.0        │
│ J      ┆ 38    ┆ 1779-1785   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1779-1785   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 32    ┆ 1786-1792   ┆ 1.0  ┆ 1.0        │
│ J      ┆ 34    ┆ 1786-1792   ┆ 2.0  ┆ 2.0        │
│ P      ┆ 35    ┆ 1786-1792   ┆ 3.5  ┆ 3.5        │
│ H      ┆ 35    ┆ 1786-1792   ┆ 3.5  ┆ 3.5        │
│ M      ┆ 36    ┆ 1786-1792   ┆ 5.0  ┆ 5.0        │
│ D      ┆ 37    ┆ 1786-1792   ┆ 6.5  ┆ 6.5        │
│ A      ┆ 37    ┆ 1786-1792   ┆ 6.5  ┆ 6.5        │
│ Z      ┆ 40    ┆ 1786-1792   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1786-1792   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 24    ┆ 1793-1799   ┆ 1.0  ┆ 1.0        │
│ J      ┆ 25    ┆ 1793-1799   ┆ 2.0  ┆ 2.0        │
│ H      ┆ 26    ┆ 1793-1799   ┆ 3.5  ┆ 3.5        │
│ M      ┆ 26    ┆ 1793-1799   ┆ 3.5  ┆ 3.5        │
│ Z      ┆ 27    ┆ 1793-1799   ┆ 5.0  ┆ 5.0        │
│ A      ┆ 29    ┆ 1793-1799   ┆ 6.0  ┆ 6.0        │
│ D      ┆ 32    ┆ 1793-1799   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 33    ┆ 1793-1799   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1793-1799   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ H      ┆ 27    ┆ 1800-1806   ┆ 1.0  ┆ 1.0        │
│ J      ┆ 28    ┆ 1800-1806   ┆ 2.0  ┆ 2.0        │
│ P      ┆ 30    ┆ 1800-1806   ┆ 4.0  ┆ 4.0        │
│ D      ┆ 30    ┆ 1800-1806   ┆ 4.0  ┆ 4.0        │
│ M      ┆ 30    ┆ 1800-1806   ┆ 4.0  ┆ 4.0        │
│ C      ┆ 31    ┆ 1800-1806   ┆ 6.5  ┆ 6.5        │
│ Z      ┆ 31    ┆ 1800-1806   ┆ 6.5  ┆ 6.5        │
│ A      ┆ 33    ┆ 1800-1806   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1800-1806   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 28    ┆ 1807-1813   ┆ 1.0  ┆ 1.0        │
│ D      ┆ 29    ┆ 1807-1813   ┆ 2.5  ┆ 2.5        │
│ M      ┆ 29    ┆ 1807-1813   ┆ 2.5  ┆ 2.5        │
│ Z      ┆ 30    ┆ 1807-1813   ┆ 4.5  ┆ 4.5        │
│ J      ┆ 30    ┆ 1807-1813   ┆ 4.5  ┆ 4.5        │
│ A      ┆ 31    ┆ 1807-1813   ┆ 6.5  ┆ 6.5        │
│ H      ┆ 31    ┆ 1807-1813   ┆ 6.5  ┆ 6.5        │
│ P      ┆ 37    ┆ 1807-1813   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1807-1813   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 25    ┆ 1814-1820   ┆ 1.5  ┆ 1.5        │
│ H      ┆ 25    ┆ 1814-1820   ┆ 1.5  ┆ 1.5        │
│ A      ┆ 26    ┆ 1814-1820   ┆ 3.0  ┆ 3.0        │
│ D      ┆ 27    ┆ 1814-1820   ┆ 4.0  ┆ 4.0        │
│ M      ┆ 31    ┆ 1814-1820   ┆ 5.0  ┆ 5.0        │
│ Z      ┆ 32    ┆ 1814-1820   ┆ 6.5  ┆ 6.5        │
│ J      ┆ 32    ┆ 1814-1820   ┆ 6.5  ┆ 6.5        │
│ P      ┆ 38    ┆ 1814-1820   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1814-1820   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 26    ┆ 1821-1827   ┆ 1.0  ┆ 1.0        │
│ H      ┆ 27    ┆ 1821-1827   ┆ 2.5  ┆ 2.5        │
│ M      ┆ 27    ┆ 1821-1827   ┆ 2.5  ┆ 2.5        │
│ P      ┆ 30    ┆ 1821-1827   ┆ 4.0  ┆ 4.0        │
│ D      ┆ 33    ┆ 1821-1827   ┆ 5.5  ┆ 5.5        │
│ A      ┆ 33    ┆ 1821-1827   ┆ 5.5  ┆ 5.5        │
│ Z      ┆ 34    ┆ 1821-1827   ┆ 7.5  ┆ 7.5        │
│ J      ┆ 34    ┆ 1821-1827   ┆ 7.5  ┆ 7.5        │
│ Test   ┆ 49    ┆ 1821-1827   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ C      ┆ 23    ┆ 1828-1834   ┆ 1.0  ┆ 1.0        │
│ J      ┆ 27    ┆ 1828-1834   ┆ 2.0  ┆ 2.0        │
│ M      ┆ 29    ┆ 1828-1834   ┆ 3.0  ┆ 3.0        │
│ D      ┆ 30    ┆ 1828-1834   ┆ 4.5  ┆ 4.5        │
│ H      ┆ 30    ┆ 1828-1834   ┆ 4.5  ┆ 4.5        │
│ P      ┆ 31    ┆ 1828-1834   ┆ 6.0  ┆ 6.0        │
│ Z      ┆ 33    ┆ 1828-1834   ┆ 7.5  ┆ 7.5        │
│ A      ┆ 33    ┆ 1828-1834   ┆ 7.5  ┆ 7.5        │
│ Test   ┆ 49    ┆ 1828-1834   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ J      ┆ 27    ┆ 1835-1841   ┆ 1.0  ┆ 1.0        │
│ M      ┆ 29    ┆ 1835-1841   ┆ 2.0  ┆ 2.0        │
│ Z      ┆ 30    ┆ 1835-1841   ┆ 3.5  ┆ 3.5        │
│ H      ┆ 30    ┆ 1835-1841   ┆ 3.5  ┆ 3.5        │
│ D      ┆ 31    ┆ 1835-1841   ┆ 5.0  ┆ 5.0        │
│ C      ┆ 35    ┆ 1835-1841   ┆ 6.0  ┆ 6.0        │
│ A      ┆ 36    ┆ 1835-1841   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 37    ┆ 1835-1841   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1835-1841   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ A      ┆ 25    ┆ 1842-1848   ┆ 1.0  ┆ 1.0        │
│ M      ┆ 27    ┆ 1842-1848   ┆ 2.0  ┆ 2.0        │
│ H      ┆ 28    ┆ 1842-1848   ┆ 3.5  ┆ 3.5        │
│ Z      ┆ 28    ┆ 1842-1848   ┆ 3.5  ┆ 3.5        │
│ C      ┆ 29    ┆ 1842-1848   ┆ 5.5  ┆ 5.5        │
│ J      ┆ 29    ┆ 1842-1848   ┆ 5.5  ┆ 5.5        │
│ D      ┆ 33    ┆ 1842-1848   ┆ 7.0  ┆ 7.0        │
│ P      ┆ 36    ┆ 1842-1848   ┆ 8.0  ┆ 8.0        │
│ Test   ┆ 49    ┆ 1842-1848   ┆ 9.0  ┆ 9.0        │
└────────┴───────┴─────────────┴──────┴────────────┘
shape: (9, 5)
┌────────┬───────┬─────────────┬──────┬────────────┐
│ player ┆ score ┆ wordle_week ┆ rank ┆ rank_right │
│ ---    ┆ ---   ┆ ---         ┆ ---  ┆ ---        │
│ str    ┆ i64   ┆ str         ┆ f64  ┆ f64        │
╞════════╪═══════╪═════════════╪══════╪════════════╡
│ M      ┆ 22    ┆ 1849-1855   ┆ 1.0  ┆ 1.0        │
│ P      ┆ 23    ┆ 1849-1855   ┆ 2.5  ┆ 2.5        │
│ Z      ┆ 23    ┆ 1849-1855   ┆ 2.5  ┆ 2.5        │
│ D      ┆ 24    ┆ 1849-1855   ┆ 4.0  ┆ 4.0        │
│ C      ┆ 25    ┆ 1849-1855   ┆ 5.5  ┆ 5.5        │

In [36]:
print(weekly_scores[0])

shape: (9, 4)
┌────────┬───────┬─────────────┬──────┐
│ player ┆ score ┆ wordle_week ┆ rank │
│ ---    ┆ ---   ┆ ---         ┆ ---  │
│ str    ┆ i64   ┆ str         ┆ f64  │
╞════════╪═══════╪═════════════╪══════╡
│ A      ┆ 27    ┆ 1681-1687   ┆ 1.0  │
│ P      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ D      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ C      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ M      ┆ 30    ┆ 1681-1687   ┆ 5.0  │
│ H      ┆ 32    ┆ 1681-1687   ┆ 6.5  │
│ Z      ┆ 32    ┆ 1681-1687   ┆ 6.5  │
│ J      ┆ 36    ┆ 1681-1687   ┆ 8.0  │
│ Test   ┆ 49    ┆ 1681-1687   ┆ 9.0  │
└────────┴───────┴─────────────┴──────┘

In [ ]:
def running_ranking(df, wordle_week):
        """
        Rank players based on overall 'score'
        """
        for week in wordle_week:

            # load wordle_week score from database
            

            running_rank_score = df.group_by("player").agg(
                pl.sum("rank").alias("running rank")
                ).sort("running rank")

            df.join(running_rank_score, on="player", how="left")

            return df

running_rank = running_ranking(weekly_scores[0])
print(running_rank)

shape: (9, 4)
┌────────┬───────┬─────────────┬──────┐
│ player ┆ score ┆ wordle_week ┆ rank │
│ ---    ┆ ---   ┆ ---         ┆ ---  │
│ str    ┆ i64   ┆ str         ┆ f64  │
╞════════╪═══════╪═════════════╪══════╡
│ A      ┆ 27    ┆ 1681-1687   ┆ 1.0  │
│ P      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ D      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ C      ┆ 29    ┆ 1681-1687   ┆ 3.0  │
│ M      ┆ 30    ┆ 1681-1687   ┆ 5.0  │
│ H      ┆ 32    ┆ 1681-1687   ┆ 6.5  │
│ Z      ┆ 32    ┆ 1681-1687   ┆ 6.5  │
│ J      ┆ 36    ┆ 1681-1687   ┆ 8.0  │
│ Test   ┆ 49    ┆ 1681-1687   ┆ 9.0  │
└────────┴───────┴─────────────┴──────┘

In [30]:
SC.ranking(df[:261])

shape: (9, 2)
┌────────┬─────────────┐
│ player ┆ total_score │
│ ---    ┆ ---         │
│ str    ┆ i64         │
╞════════╪═════════════╡
│ M      ┆ 115         │
│ C      ┆ 117         │
│ H      ┆ 121         │
│ P      ┆ 122         │
│ A      ┆ 124         │
│ D      ┆ 125         │
│ Z      ┆ 126         │
│ J      ┆ 132         │
│ Test   ┆ 198         │
└────────┴─────────────┘

In [21]:
print(df['wordle_num'].unique())

shape: (173,)
Series: 'wordle_num' [i64]
[
	1681
	1682
	1683
	1684
	1685
	…
	1849
	1850
	1851
	1852
	1853
]

In [ ]:
SC.ranking(df)

shape: (9, 2)
┌────────┬─────────────┐
│ player ┆ total_score │
│ ---    ┆ ---         │
│ str    ┆ i64         │
╞════════╪═════════════╡
│ C      ┆ 684         │
│ M      ┆ 701         │
│ H      ┆ 724         │
│ A      ┆ 740         │
│ J      ┆ 752         │
│ Z      ┆ 761         │
│ D      ┆ 762         │
│ P      ┆ 790         │
│ Test   ┆ 1195        │
└────────┴─────────────┘

In [20]:
test = df.group_by("player").agg(
    pl.col("score").sum().alias("total_score")
).sort("total_score")

print(test)

shape: (9, 2)
┌────────┬─────────────┐
│ player ┆ total_score │
│ ---    ┆ ---         │
│ str    ┆ i64         │
╞════════╪═════════════╡
│ C      ┆ 684         │
│ M      ┆ 701         │
│ H      ┆ 724         │
│ A      ┆ 740         │
│ J      ┆ 752         │
│ Z      ┆ 761         │
│ D      ┆ 762         │
│ P      ┆ 790         │
│ Test   ┆ 1195        │
└────────┴─────────────┘

In [22]:
# db = Database()

# for result in result_lines:
#     date, player, wordle, score = result
#     db.save_score(date, player, wordle, score)

In [58]:
get_scores = db.leaderboard()
print(get_scores)

NameError: name 'db' is not defined